.TH "src/searching.cpp" 3 "Wed Feb 27 2019" "Linear/Binary Search" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/searching.cpp \- Implementing linear and binary search (iterative version)\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <iterator>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBvalue_type\fP = int"
.br
.RI "Simple alias to help code maintenance\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBvalue_type\fP * \fBlsearch\fP (const \fBvalue_type\fP *first, const \fBvalue_type\fP *last, \fBvalue_type\fP value)"
.br
.RI "Implements an iterative linear seach on an range [first; last) of integers\&. "
.ti -1c
.RI "const \fBvalue_type\fP * \fBbsearch\fP (const \fBvalue_type\fP *first, const \fBvalue_type\fP *last, \fBvalue_type\fP value)"
.br
.RI "Implements an interative binary search on an array of integers\&. "
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementing linear and binary search (iterative version)\&. 


.PP
\fBAuthor:\fP
.RS 4
Selan, imns1ght 
.RE
.PP
\fBDate:\fP
.RS 4
February, 24th 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "const \fBvalue_type\fP* bsearch (const \fBvalue_type\fP * first, const \fBvalue_type\fP * last, \fBvalue_type\fP value)"

.PP
Implements an interative binary search on an array of integers\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfirst\fP Pointer to the first element in the range\&. 
.br
\fIlast\fP Pointer to the last element in the range\&. 
.br
\fIvalue\fP The target value we are looking for within the range\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A pointer to the target value within the range; or last, in case the value is not in the range\&. 
.RE
.PP

.SS "const \fBvalue_type\fP* lsearch (const \fBvalue_type\fP * first, const \fBvalue_type\fP * last, \fBvalue_type\fP value)"

.PP
Implements an iterative linear seach on an range [first; last) of integers\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfirst\fP Pointer to the first element in the range\&. 
.br
\fIlast\fP Pointer past the last valid element in the range\&. 
.br
\fIvalue\fP The target value we are looking for within the range\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A pointer to the target value within the range; or last, in case the value is not in the range\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Linear/Binary Search from the source code\&.
